### PR TITLE
Fixed #17

### LINKED ISSUE #17: Bug: featured items thumbnails disappear on large viewport with Firefox
Given I browse https://wowthemesnet.github.io/mediumish-theme-jekyll/ on Firefox 64.0, the featured items loose their background, thumbnail height equals zero when viewport is larger than 1200px

Screenshot

mediumish-2018-12-20 22 18 34

### PR DESCRIPTION
**Pull request by InfoSecRavindra**

### CODE REVIEW

**Comment by LJamesHu** [comment]
This doesn't do the same thing as the code it replaces.

In this case it fixes the size to 290px, but there is a case that if you increase truncatewords:25 in _includes/featuredbox.html that the box will be larger. What min-height does is makes sure that even if truncatewords is 0, that the image isn't turned into this 100px height thumbnail. But if truncatewords is really high, that it will dynamically adjust to the right size height to fit the box.

**Comment by InfoSecRavindra** [comment]
It is using table layout so it will increate it's height if content doesn't fit.

**Comment by LJamesHu** [comment]
You fix it in Firefox to break it in Chrome. When I apply the change in Chrome, when the post is smaller than the `height`, it adjusts down below the height, whereas `min-height` keeps the image at minimum 200px.

**Comment by InfoSecRavindra** [comment]
Same behavior in Firefox but if we change `height` to `min-height' then Firefox will show white area instead image. I am looking for a solution that works on both browsers without breaking anything.

**Pull request merged**
